main: com.winthier.adviceanimals.AdviceAnimalsPlugin

name: AdviceAnimals
description: Talking animals
version: 0.3
api-version: '1.21.10'

author: StarTux
website: https://cavetale.com

depend: [Core]
softdepend: []

commands:
  AdviceAnimals:
    aliases: [ aa ]
    description: AdviceAnimals command interface
    permission: adviceanimals.aa
    usage: |-
      Usage:
      /aa reload
      /aa save
      /aa info [name] - Info (hit)
      /aa rename [name] - Rename animal (hit)
      /aa teleport - Teleport animal (hit)
      /aa ignore - Toggle ignore
      /aa locate <name> - Teleport to animal
      /aa select <name> - Select animal (hit)
      /aa create <name> - Create animal (hit)
      /aa tasks start|stop - Start or stop bg tasks
      /aa record start|stop|cancel - Record your path
      /aa record save <name> - Save a recording

permissions:
  adviceanimals.aa:
    description: Use the command interface
    default: op
