name: AdviceAnimals
description: Talking animals
author: StarTux
version: 0.3
api-version: 1.13
website: https://cavetale.com
main: com.winthier.adviceanimals.AdviceAnimalsPlugin
softdepend: [ Multiverse-Core ]
commands:
  AdviceAnimals:
    aliases: [ aa ]
    description: AdviceAnimals command interface
    permission: adviceanimals.aa
permissions:
  adviceanimals.aa:
    description: Use the command interface
    default: op
